In [1]:
%run ./utils.ipynb

In [2]:
dummy_dinamico = False
dummy_estatico = False

In [3]:
csv_path = "Agregados_por_setores_cor_ou_raca_BR_csv/Agregados_por_setores_cor_ou_raca_BR.csv"

In [4]:
# investigar Cidades com mais de x habitantes

In [5]:
desired_columns = [
    'CD_SETOR', 
    'V01317', 
    'V01318', 
    'V01319', 
    'V01320', 
    'V01321'
]

df = pd.read_csv(csv_path, sep = ';', usecols=desired_columns)
df['CD_SETOR'] = df['CD_SETOR'].astype('str')

cols_to_clean = ['V01317', 'V01318', 'V01319', 'V01320', 'V01321']
df[cols_to_clean] = df[cols_to_clean].replace('X', 0)
df = df.fillna(0)
df[cols_to_clean] = df[cols_to_clean].astype('int32')

df['pop_total'] = df[cols_to_clean].sum(axis=1)

C:\Users\renan\AppData\Local\Temp\ipykernel_39316\4209179137.py:10: DtypeWarning: Columns (1,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path, sep = ';', usecols=desired_columns)

In [6]:
df['COD_MUNICIPIO'] = df['CD_SETOR'].str[:6]
df['COD_ESTADO'] = df['CD_SETOR'].str[:2]

In [7]:
df.head()

,CD_SETOR,V01317,V01318,V01319,V01320,V01321,pop_total,COD_MUNICIPIO,COD_ESTADO
0,110001505000002,312,87,0,514,13,926,110001,11
1,110001505000003,189,25,0,336,6,556,110001,11
2,110001505000004,71,14,0,135,0,220,110001,11
3,110001505000006,255,54,0,460,14,783,110001,11
4,110001505000007,229,49,0,459,10,747,110001,11

In [8]:
pop_total_municipios = df.groupby(['COD_MUNICIPIO','COD_ESTADO'])[['pop_total']].sum()

In [9]:
# 2. Filter for sums greater than a value{
municipios_grandes = pop_total_municipios[pop_total_municipios['pop_total'] > 100000].reset_index()

In [10]:
municipios_grandes

    COD_MUNICIPIO COD_ESTADO  pop_total
0          110012         11     123674
1          110020         11     456992
2          120040         12     361827
3          130190         13     103249
4          130250         13     101702
..            ...        ...        ...
314        521880         52     224767
315        522045         52     155397
316        522140         52     141589
317        522185         52     198578
318        530010         53    2796243

[319 rows x 3 columns]

In [11]:
estado = 'RS'
municipio = '4314902'
shp_path = f"{estado}_setores_CD2022/{estado}_setores_CD2022.shp"

seg_profile_mun(shp_path, csv_path, municipio, plot_dinamico = dummy_dinamico, plot_estatico = dummy_estatico)

C:\Users\renan\anaconda3\Lib\site-packages\pyogrio\core.py:36: RuntimeWarning: Could not detect PROJ data files. Set PROJ_LIB environment variable to the correct path.
  _init_proj_data()
C:\Users\renan\AppData\Local\Temp\ipykernel_39316\1879524485.py:15: DtypeWarning: Columns (1,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path, sep = ';', usecols=desired_columns)
C:\Users\renan\AppData\Local\Temp\ipykernel_39316\1879524485.py:23: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_gdf = merged_gdf.fillna(0)
C:\Users\renan\anaconda3\Lib\site-packages\segregation\singlegroup\spatial_dissim.py:48: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w_object = Queen.from_dataframe(data)

Dissimilarity: 0.36938877371482537
Spatial Dissimilarity: 0.2862184030564052
Gini: 0.48854095748836385
Entropy: 0.12980799191107342
Isolation: 0.36469467525756316
Dist. Decay Isolation: 0.32391461781522224
Rel. Concentration: -0.10650809891200008
Rel. Centralization: -0.10156531362133592
Rel. Clustering: 0.5956711862979596